/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Hello VuePress",
  "description": "Just playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "快速开始",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2e8a864e",
      "path": "/"
    },
    {
      "title": "Card",
      "frontmatter": {},
      "regularPath": "/componentDocs/card.html",
      "relativePath": "componentDocs/card.md",
      "key": "v-47ecb233",
      "path": "/componentDocs/card.html"
    }
  ],
  "themeConfig": {
    "sidebar": [
      "/",
      "/componentDocs/card"
    ]
  }
}